name: 'Application-security-scan'

description: 'A GitHub Action to perform an application security scan using ZAP.'
author: 'Your Name or Organization'
inputs:
  zap_token:
    description: 'ZAP API token'
    required: true
  zap_target:
    description: 'Target URL for ZAP scan'
    required: true
  zap_format:
    description: 'Format for ZAP scan'
    required: true
    default: 'openapi'
  zap_cmd_options:
    description: 'Additional command options for ZAP'
    required: false
    default: '-a'
  x_api_key:
    description: 'API key for authorization'
    required: true

runs:
  using: 'composite'
  steps:
    - name: ZAP Scan
      uses: zaproxy/action-api-scan@v0.9.0
      with:
        token: ${{ inputs.zap_token }}
        format: ${{ inputs.zap_format }}
        target: ${{ inputs.zap_target }}
        cmd_options: ${{ inputs.zap_cmd_options }}
      env:
        ZAP_AUTH_HEADER_VALUE: "x-api-key=${{ inputs.x_api_key }}"
